services:
  hadoop:
    build: .
    ports:
        - 9870:9870
        - 8088:8088
        - 9000:9000
        - 9866:9866
        - 9864:9864
    volumes:
        - hdfs:/home/hadoop/hdfs
volumes:
  hdfs:
  
